
CREATE TABLE IF NOT EXISTS password_info(
    id INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
    username VARCHAR(200) NOT NULL,
    password BINARY(60) NOT NULL,
    website VARCHAR(200) NOT NULL
);